// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1KeEsegniLhyeJW7QnTLXOBlptFSXJTg',
    appId: '1:365772345799:web:a3a935236b0f70bcfb09e2',
    messagingSenderId: '365772345799',
    projectId: 'beyondlanguage-478e8',
    authDomain: 'beyondlanguage-478e8.firebaseapp.com',
    storageBucket: 'beyondlanguage-478e8.appspot.com',
    measurementId: 'G-9MQ4Q3W9Y0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAc4FD-S1CLsYwXvKeDwZj4w_czbaPlS2E',
    appId: '1:365772345799:android:e63d7648fe1c2e78fb09e2',
    messagingSenderId: '365772345799',
    projectId: 'beyondlanguage-478e8',
    storageBucket: 'beyondlanguage-478e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgwGbh45dpzJilbNahox_as9QNAKY2STA',
    appId: '1:365772345799:ios:b0a8dad7e918fe4ffb09e2',
    messagingSenderId: '365772345799',
    projectId: 'beyondlanguage-478e8',
    storageBucket: 'beyondlanguage-478e8.appspot.com',
    iosBundleId: 'com.example.languageApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgwGbh45dpzJilbNahox_as9QNAKY2STA',
    appId: '1:365772345799:ios:b0a8dad7e918fe4ffb09e2',
    messagingSenderId: '365772345799',
    projectId: 'beyondlanguage-478e8',
    storageBucket: 'beyondlanguage-478e8.appspot.com',
    iosBundleId: 'com.example.languageApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1KeEsegniLhyeJW7QnTLXOBlptFSXJTg',
    appId: '1:365772345799:web:a393b3d335bee7fafb09e2',
    messagingSenderId: '365772345799',
    projectId: 'beyondlanguage-478e8',
    authDomain: 'beyondlanguage-478e8.firebaseapp.com',
    storageBucket: 'beyondlanguage-478e8.appspot.com',
    measurementId: 'G-VY8P638WNC',
  );
}
